[package]
name = "chaff-cli"
description = "Command line for Chaff - a library for implementing Website Fingerprinting defences."
version = "0.1.0"
readme = "README.md"
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
chaff = { version = "0.1.0", path = "../chaff/" }

bpaf = { version = "0.9.22", features = ["derive"] }
