[package]
name = "chaff-capture"
description = "Trace capture utilities for Chaff."
version = "0.1.0"
readme = "README.md"
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
chaff = { version = "0.1.0", path = "../chaff/" }
mac_address = "1.1.8"
pcap = "2.4.0"

[[example]]
name = "capture"
path = "examples/capture.rs"
