[package]
name = "chaff-sim"
description = "Simulator for the Chaff Framework"
version = "0.1.0"
readme = "README.md"
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
chaff = { version = "0.1.0", path = "../chaff/" }
chaff-capture = { version = "0.1.0", path = "../chaff-capture/" }
rand.workspace = true
