[package]
name = "chaff"
description = "Library for implementing and testing Website Fingerprinting defences"
version = "0.1.0"
readme = "README.md"
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
borsh = ["dep:borsh"]

[dependencies]
borsh = { workspace = true, optional = true, features = ["de_strict_order", "derive"] }
rand.workspace = true
rand_distr.workspace = true

[dev-dependencies]
tempfile.workspace = true
