name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-msrv:
    name: Check MSRV matches Arti
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check MSRV matches Arti
        run: ./scripts/check_msrv.sh

  build-and-check:
    name: Build and Check
    needs: check-msrv
    strategy:
      matrix:
        include:
          - arch: x64
            runs_on: ubuntu-latest
          - arch: arm64
            runs_on: ubuntu-24.04-arm
          - arch: arm64
            runs_on: macos-latest
    runs-on: ${{ matrix.runs_on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      #- uses: DeterminateSystems/magic-nix-cache-action@main # disabled due to long upload times
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Build
        run: nix build
      - name: Check
        run: nix flake check
